version: '3.5'
services:
  reverse-proxy:
    image: reverse-proxy
    build: .
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    extra_hosts: 
        - "host.docker.internal:host-gateway"
    volumes:
        - /etc/letsencrypt/:/etc/letsencrypt/

