name: Unit tests

on: [pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      
      - name: Install requirements and run unit tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
          python3 -m pytest tests --verbose
 
      - name: Time reporter
        uses: DeviesDevelopment/workflow-timer

